# Generated by Django 2.2.1 on 2019-06-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='owner',
            new_name='player',
        ),
    ]
