# Generated by Django 2.2.1 on 2019-06-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190625_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='playerscore',
            old_name='player',
            new_name='owner',
        ),
    ]
